# Generated by nostromo v0.5.0
# ----------------------------

module "netezza" {
    source                  =       "git::https://stash.synchronoss.net/scm/terraform/os-server-v2.git?ref=v0.6"

    # Generic Input Variables
    net_name1               =       "Analytics_Network"

    # Public IP variables
    fip_count               =       0
    pool_name               =       "External_Floating_IP_Network"

    # Server variables
    servername              =       "netezza"
    project_name            =       "Analytics"
    image                   =       "CentOS-6.7-x86_64"
    flavor                  =       "r3.2xlarge"
    keyname                 =       "velocity"
    ingress-sg              =       "default"

    # Chef Input Variables
    CHEF_SERVER             =       "https://chef-pabet-redirect.sncrcorp.net:443"
#    CHEF_PROXY              =       ""
    CHEF_ENV                =       "velbda-poc"
#    CHEF_ROLES              =       ""
    CHEF_ORG                =       "vel-bda"

    # Network Input Varaibles
    DOMAIN                  =       "bda.poc.velocity-va.sncrcorp.net"
    NODENAME                =       "netezza"

    # Additional 1 volume

    server_5vol_count       =       1
    mountpoint1             =       "/opt"
    device_name1            =       "/dev/xvp"
    device_name2            =       "/dev/xvq"
    device_name3            =       "/dev/xvr"
    device_name4            =       "/dev/xvs"
    device_name5            =       "/dev/xvt"
    volume_size1            =       50
    volume_size2            =       1024
    volume_size3            =       1024
    volume_size4            =       1024
    volume_size5            =       1024

    # PDNS server URL

    pdns_server_url         =       "http://10.48.0.31:8081"
}
